blog/urls.py
from django.urls import path
from . import views

app_name = "post"
urlpatterns = [
    path('', views.post_index, name="index"),
    # post
    path('detail/<slug:slug>', views.post_detail, name='detail'),
    path('create/', views.post_create, name="create"),
    path('update/<int:id>/<slug:slug>', views.post_update, name="update"),
    path('delete/<int:id>/<slug:slug>', views.post_delete, name="delete"),
    # category
    path('categories/', views.category_list, name='category_list'),
    path('category/<int:id>/<slug:slug>', views.category, name='category'),
    path('create/category', views.add_category, name="add_category"),
    path('update/category/<int:id>/<slug:slug>',
         views.update_category, name="update_category"),
    path('delete/category/<int:id>/<slug:slug>',
         views.delete_category, name="delete_category"),
    # tag
    path('tags/', views.tag_list, name='tag_list'),
    path('tag/<int:id>/<slug:slug>', views.tag, name='tag'),
    path('create/tag', views.add_tag, name="add_tag"),
    path('update/tag/<int:id>/<slug:slug>',
         views.update_tag, name="update_tag"),
    path('delete/tag/<int:id>/<slug:slug>',
         views.delete_tag, name="delete_tag"),
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('delete/profile/<int:id>/', views.delete_profile, name="delete_profile"),
]

mySite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls'))
]

static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base/404_page.html
<style>
body{margin-top:20px;}
.error-page {
    text-align: center;
	background: #fff;
	border-top: 1px solid #eee;
}
.error-page .error-inner {
	display: inline-block;
}
.error-page .error-inner h1 {
	font-size: 140px;
	text-shadow: 3px 5px 2px #3333;
	color: #006DFE;
	font-weight: 700;
}
.error-page .error-inner h1 span {
	display: block;
	font-size: 25px;
	color: #333;
	font-weight: 600;
	text-shadow: none;
}
.error-page .error-inner p {
	padding: 20px 15px;
}
.error-page .search-form {
	width: 100%;
	position: relative;
}
.error-page .search-form input {
	width: 400px;
	height: 50px;
	padding: 0px 78px 0 30px;
	border: none;
	background: #f6f6f6;
	border-radius: 5px;
	display: inline-block;
	margin-right: 10px;
	font-weight:400;
	font-size:14px;
}
.error-page .search-form input:hover{
	padding-left:35px;
}
.error-page .search-form .btn {
	width: 80px;
	height: 50px;
	border-radius: 5px;
	cursor: pointer;
	background: #006DFE;
	display: inline-block;
	position: relative;
	top: -2px;
}
.error-page .search-form .btn i{
	font-size:16px;
}
.error-page .search-form .btn:hover{
	background:#333;
}
</style>
<section class="error-page section">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 offset-lg-3 col-12">
				<!-- Error Inner -->
				<div class="error-inner">
					<h1>404<span>Oop's sorry we can't find that page!
</span></h1>
						<button class="btn" type="submit" style="font-family: Arial, Helvetica, sans-serif;font-size:15px"><a href="{% url 'home:index' %}">Back Home</a></button>
				</div>
				<!--/ End Error Inner -->
			</div>
		</div>
	</div>
</section>

templates/base/500_page.html
<style>
body{margin-top:20px;}
.error-page {
    text-align: center;
	background: #fff;
	border-top: 1px solid #eee;
}
.error-page .error-inner {
	display: inline-block;
}
.error-page .error-inner h1 {
	font-size: 140px;
	text-shadow: 3px 5px 2px #3333;
	color: #006DFE;
	font-weight: 700;
}
.error-page .error-inner h1 span {
	display: block;
	font-size: 25px;
	color: #333;
	font-weight: 600;
	text-shadow: none;
}
.error-page .error-inner p {
	padding: 20px 15px;
}
.error-page .search-form {
	width: 100%;
	position: relative;
}
.error-page .search-form input {
	width: 400px;
	height: 50px;
	padding: 0px 78px 0 30px;
	border: none;
	background: #f6f6f6;
	border-radius: 5px;
	display: inline-block;
	margin-right: 10px;
	font-weight:400;
	font-size:14px;
}
.error-page .search-form input:hover{
	padding-left:35px;
}
.error-page .search-form .btn {
	width: 80px;
	height: 50px;
	border-radius: 5px;
	cursor: pointer;
	background: #006DFE;
	display: inline-block;
	position: relative;
	top: -2px;
}
.error-page .search-form .btn i{
	font-size:16px;
}
.error-page .search-form .btn:hover{
	background:#333;
}
</style>
<section class="error-page section">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 offset-lg-3 col-12">
				<!-- Error Inner -->
				<div class="error-inner">
					<h1>500<span>OOOPS!!
SOMETHING WENT WRONG.</span></h1>
						<button class="btn" type="submit" style="font-family: Arial, Helvetica, sans-serif;font-size:15px"><a href="{% url 'home:index' %}">Back Home</a></button>
				</div>
				<!--/ End Error Inner -->
			</div>
		</div>
	</div>
</section>

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="{% block description %}{% endblock description %}" />
        <meta name="keywords" content="{% block keywords %}{% endblock keywords %}" />
        <meta name="author" content="" />
        <title>{% block title %} {% endblock title %}</title>
        <link rel="icon" type="image/x-icon" href="{% block icon %}{% endblock icon %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/blog-style.css' %}" rel="stylesheet" />
    </head>
<body id="page-top">
  <!-- Page Content-->
	{% block content %}
	{% endblock content %}
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>

</body>

</html>

templates/base/message.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

templates/base/navbar.html
{% load static %}
<!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="sideNav">
            <a class="navbar-brand js-scroll-trigger" href="{% url 'home:index' %}#page-top">
                {% if content %}
                {% for item in content %}
                    <span class="d-block d-lg-none">{{item.name.upper}} {{item.surName.upper}}</span>
                    {% if item.image %}
                        <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{{item.image.url}}" alt="..." /></span>
                    {% else %}
                    <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'assets/img/profile.png' %}" alt="..." /></span>
                    {% endif %}
                {% endfor %}
                {% else %}
                    <span class="d-block d-lg-none">My Site</span>
                    <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'assets/img/profile.png' %}" alt="..." /></span>
                {% endif %}
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home:index' %}#about">About</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home:index' %}#experience">Experience</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home:index' %}#education">Education</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home:index' %}#skills">Skills</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home:index' %}#interests">Interests</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home:index' %}#awards">Awards</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'post:index' %}">Blog</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home:contact' %}">Contact</a></li>
                </ul>
            </div>
        </nav>